---
# Pug options
pretty: true

# Header info
firstName: Nigel
lastName: Baillie
bulletPoints:
  - Software engineer
  - University of Michigan alumnus
  - American in Tokyo

email: nigel@baillie.dev
github: https://github.com/Resonious
resume: /NigelBaillieSoftwareEngineer.pdf

# Project entries
projects:
  - name: Teleport
    path: teleport
    logline: VR remote presence
    image:
      src: /videos/teleport-preview.webm
      anchor: center
      height: 370px
    video:
      src: /videos/teleport-vr.webm
    descriptionDoc: teleport-description.md
    date: 2023
    stack:
      - TypeScript
      - WebRTC
      - THREE.js
      - Raspberry Pi

  - name: riregi
    path: riregi
    logline: Offline cash register app
    image:
      src: /videos/riregi-preview.webm
      anchor: top
      height: 500px
    video:
      src: /videos/riregi.webm
    descriptionDoc: riregi-description.md
    date: 2023
    stack:
      - Dart
      - Flutter
      - Zig

  - name: hook.snd.one
    path: sndone
    logline: No-signup webhook inspector
    image:
      src: /videos/sndone-preview.webm
      anchor: center
      height: 350px
    video:
      src: /videos/sndone.webm
    descriptionDoc: sndone-description.md
    date: 2023
    stack:
      - Rust
      - Hyper
    source: https://github.com/Resonious/hook

  - name: Exposure
    path: exposurerb
    logline: Better intellisense for Ruby projects
    image:
      src: /videos/exposure-preview.webm
      anchor: bottom
      height: 400px
    video:
      src: /videos/exposure.webm
    descriptionDoc: exposure-description.md
    date: 2022
    stack:
      - C
      - Ruby
    source: https://github.com/Resonious/exposure

  - name: mkdesktop
    path: mkdesktop
    logline: Linux app for managing .desktop files
    image:
      src: /videos/mkdesktop-preview.webm
      anchor: center
      height: 330px
    video:
      src: /videos/mkdesktop.mp4
    description:
      - I run Linux on my daily driver. Usually, the built-in package manager works like a dream. Most notably,
        the package manager will create a desktop launcher for any app you install. But what if I want to skip
        the package manager and install something from source? Remembering how .desktop files work and where
        to put them was never my strong suit. This `mkdesktop` app provides a GUI for creating custom app launchers.
      - I built this using Rust and GTK. It also works as a CLI, letting you CRUD your custom desktop launchers
        from your shell as well. The GUI is GTK, put together using the Glade editor.
      - The app uses xdg-desktop-menu under the hood, and so it will work with any Linux desktop. When I first
      - built this, I was using GNOME, and now I'm on Sway and it still works like a dream.
    date: 2019
    stack:
      - Rust
      - GTK3
      - Builder
    source: https://github.com/Resonious/mkdesktop

  - name: One After Another
    path: one-after-another
    logline: Cooperate with your past self.
    image:
      src: /videos/oato-preview.webm
      anchor: center
      height: 600px
    video:
      src: /videos/oato-gameplay.webm
    description:
      - This was a solo project for the University of Michigan's EECS 494. The goal of the project was to come up
        with a novel idea, and thoroughly explore it in a playable prototype.
      - My original idea was something along the lines of having real time combat where players
        controlled multiple characters. I was thinking along the lines of recording a routine
        for one character, and then switching over to another character to record their routine.
      - I cooked up an input recording/playback system and as I was messing around with it, I
        found that often what I wanted to do as one character was walk to a new location. The
        problem with that was that I would then switch back to the other character, and the
        character I just moved would proceed to walk itself into walls or jump off cliffs.
        I could have explored some way to manually specify when you're recording, but that
        struck me as too confusing.
      - In the end, I ended up scrapping the whole combat idea, and went with a simple platformer.
        Instead of recording controls and switching between characters, however, I made it so
        that once you reach the end of a level, you respawn at the beginning alongside a ghost
        of your previous run.
    date: 2017
    stack:
      - C#
      - Unity
    link: https://drive.google.com/file/d/1phdvL61pEeFksbCAzC4vA7MpSdcvbsqG/view?usp=sharing

  - name: Wrecked
    path: wrecked
    logline: Demolish your friends with jet-powered construction vehicles.
    image:
      src: /videos/wrecked-preview.webm
      anchor: bottom
      height: '400px'
    video:
      src: /videos/wrecked-trailer.webm
    description:
      - This was built in a team of four for the final project of U-M's EECS 494 over the course
        of about two months. This particular team of four consisted of me, Jennifer Dailey,
        Joseph Pohlman, and Adilah Ku.
      - The assignment was to make a game to be played during the EECS 494 showcasee
        at the end of the semester. The showcase is a big event where everyone invites
        their friends and family, so the final project games ought to be easy to pick up
        and quickly engaging, similar to old arcade games. We figured a four player competitive
        game was a good fit, and decided to go with an over-the-top insane type of theme.
        So, flying construction vehicles with wrecking balls it was.
      - Pretty embarrassing, but I did the voiceover for that trailer.
    date: 2017
    stack:
      - C#
      - Unity
    link: https://drive.google.com/file/d/1YEMy9K25qMliJfmSa2uLyH7G1Z-rnMuD/view?usp=sharing

  - name: Crattlecrute
    path: crattlecrute
    logline: '"From scratch" game project, online play and custom physics'
    image:
      src: /videos/crattlecrute-preview.webm
      anchor: center
      height: 500px
    video:
      src: /videos/crattlecrute-gameplay.webm
    descriptionDoc: crattlecrute-description.md
    date: 2015 - 2016
    stack:
      - C
      - 'SDL2'
      - 'RakNet'
      - 'MRuby'
    source: https://github.com/Resonious/crattlecrute

  - name: A Duel with The Devil
    path: a-duel-with-the-devil
    logline: Side-view grid-based tactical combat.
    image:
      src: /videos/dwtd-preview.webm
      anchor: center
      height: 400px
    video:
      src: /videos/dwtd-good-fixed.webm
    descriptionDoc: dwtd-description.md
    date: 2015
    stack:
      - C++
      - 'SDL2'
      - 'RakNet'
    source: https://github.com/Resonious/dwtd
    link: https://github.com/Resonious/dwtd/releases/tag/ld33
    entry: http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=38940

  - name: Breaker
    path: breaker
    logline: Punch blocks until you die.
    image:
      src: /videos/breaker-preview.webm
      anchor: bottom
      height: 400px
    video:
      src: /videos/breaker-good-fixed.webm
    description:
      - My entry for Ludum Dare 31, my second Ludum Dare. I originally described this one as
        "a mix between Tetris and Minecraft". Blocks fall from the sky, and the goal is just to
        punch them. If a block lands on you while you're not either dodging or jumping, you are
        crushed and it's game over. Some blocks shoot projectiles, some explode, and some contain
        a powerup that can help you clear large stacks of blocks. Eventually, a black hole appears,
        stirring the madness.
      - There are several different types of blocks. A red block that does nothing, a blue one that
        shoots bullets (which do damage other blocks), a metal block that takes a ton of hits to
        break, a bomb block that explodes 3 seconds after taking damage, and a chest block that
        reveals a powerup upon breaking.
      - 'This one turned out rather fun, I think. It got rated #90 in the "fun" category for LD31.'
    date: December 2014
    stack:
      - 'LiveScript'
      - 'Phaser'
    source: https://github.com/Resonious/breaker
    link: http://resonious.github.io/breaker
    entry: http://ludumdare.com/compo/ludum-dare-31/?action=preview&uid=38940

  - name: Gray Area
    path: gray-area
    logline: Navigate the world and its inverse.
    image:
      src: /videos/gray-area-preview.webm
      anchor: center
      height: 400px
    video:
      src: /videos/gray-area-good-fixed.webm
    description:
      - My entry for Ludum Dare 30. This was my first Ludum Dare entry, and probably
        my first ever full game. I had done game development before this but never
        actually finished anything. I suppose the 48 hour time limit pushed me over
        the edge.
      - The game is mostly just black and white. There is a black character, and a white character.
        The black character only collides with black shapes and vice versa. The fun part is that,
        for instance, a black shape can overlap another black shape, creating a new opening for the
        white character to jump into.
    date: August 2014
    stack:
      - 'LiveScript'
      - 'Phaser'
    source: https://github.com/Resonious/gray-area
    link: http://resonious.github.io/gray-area/
    entry: http://ludumdare.com/compo/ludum-dare-30/?action=preview&uid=38940
