---
# Pug options
pretty: true

# Header info
firstName: Nigel
lastName: Baillie
bulletPoints:
  - Software engineer
  - University of Michigan student
  - Video game enthusiast

# Project entries
projects:
  - name: Gray Area
    logline: Navigate the world and its inverse.
    image: images/gray-area-preview.webp
    imageAnchor: center

  - name: A Duel with The Devil
    logline: Side-view grid-based tactical combat.
    image: images/dwtd-preview.webp
    imageAnchor: center

  - name: Breaker
    logline: Punch blocks until you die.
    image: images/breaker-preview.webp
    imageAnchor: bottom
