---
# Pug options
pretty: true

# Header info
firstName: Nigel
lastName: Baillie
bulletPoints:
  - Software engineer
  - University of Michigan alumnus
  - Video game enthusiast

email: bnigel@umich.edu
github: https://github.com/Resonious
resume: /NigelBaillieResume.pdf

# Project entries
sideProjects:
  - name: Crattlecrute
    path: crattlecrute
    logline: An unfinished attempt to create a game "from scratch"
    image:
      src: /videos/crattlecrute-preview.webm
      anchor: center
      height: 500px
    video:
      src: /videos/crattlecrute-gameplay.webm
    descriptionDoc: crattlecrute-description.md
    source: https://github.com/Resonious/crattlecrute

schoolProjects:
  - name: One After Another
    path: one-after-another
    logline: Cooperate with your past self.
    image:
      src: /videos/oato-preview.webm
      anchor: center
      height: 600px
    video:
      src: /videos/oato-gameplay.webm
    description:
      - This was a solo project for U-M's EECS 494. The goal of the project was to come up
        with a novel idea, and thoroughly explore it in a playable prototype.
      - My original idea was something along the lines of having real time combat where players
        controlled multiple characters. I was thinking along the lines of recording a routine
        for one character, and then switching over to another character to record their routine.
      - I cooked up an input recording/playback system and as I was messing around with it, I
        found that often what I wanted to do as one character was walk to a new location. The
        problem with that was that I would then switch back to the other character, and the
        character I just moved would proceed to walk itself into walls or jump off cliffs.
        I could have explored some way to manually specify when you're recording, but that
        struck me as too confusing.
      - In the end, I ended up scrapping the whole combat idea, and went with a simple platformer.
        Instead of recording controls and switching between characters, however, I made it so
        that once you reach the end of a level, you respawn at the beginning alongside a ghost
        of your previous run.
    link: https://drive.google.com/file/d/1phdvL61pEeFksbCAzC4vA7MpSdcvbsqG/view?usp=sharing

  - name: Wrecked
    path: wrecked
    logline: Demolish your friends with jet-powered construction vehicles.
    image:
      src: /videos/wrecked-preview.webm
      anchor: bottom
      height: '400px'
    video:
      src: /videos/wrecked-trailer.webm
    description:
      - This was built in a team of four for the final project of U-M's EECS 494 over the course
        of about two months. This particular team of four consisted of me, Jennifer Dailey,
        Joseph Pohlman, and Adilah Ku.
      - The assignment was to make a game to be played during the EECS 494 showcasee
        at the end of the semester. The showcase is a big event where everyone invites
        their friends and family, so the final project games ought to be easy to pick up
        and quickly engaging, similar to old arcade games. We figured a four player competitive
        game was a good fit, and decided to go with an over-the-top insane type of theme.
        So, flying construction vehicles with wrecking balls it was.
      - Also, yes, I did the voiceover for that trailer.
    link: https://drive.google.com/file/d/1YEMy9K25qMliJfmSa2uLyH7G1Z-rnMuD/view?usp=sharing

ldProjects:
  - name: Gray Area
    path: gray-area
    logline: Navigate the world and its inverse.
    image:
      src: /videos/gray-area-preview.webm
      anchor: center
      height: 400px
    video:
      src: /videos/gray-area-good-fixed.webm
    description:
      - My entry for Ludum Dare 30. This was my first Ludum Dare entry, and probably
        my first ever full game. I had done game development before this but never
        actually finished anything. I suppose the 48 hour time limit pushed me over
        the edge.
      - The game is mostly just black and white. There is a black character, and a white character.
        The black character only collides with black shapes and vice versa. The fun part is that,
        for instance, a black shape can overlap another black shape, creating a new opening for the
        white character to jump into.
    source: https://github.com/Resonious/gray-area
    link: http://resonious.github.io/gray-area/
    entry: http://ludumdare.com/compo/ludum-dare-30/?action=preview&uid=38940

  - name: Breaker
    path: breaker
    logline: Punch blocks until you die.
    image:
      src: /videos/breaker-preview.webm
      anchor: bottom
      height: 400px
    video:
      src: /videos/breaker-good-fixed.webm
    description:
      - My entry for Ludum Dare 31, my second Ludum Dare. I originally described this one as
        "a mix between Tetris and Minecraft". Blocks fall from the sky, and the goal is just to
        punch them. If a block lands on you while you're not either dodging or jumping, you are
        crushed and it's game over. Some blocks shoot projectiles, some explode, and some contain
        a powerup that can help you clear large stacks of blocks. Eventually, a black hole appears,
        stirring the madness.
      - There are several different types of blocks. A red block that does nothing, a blue one that
        shoots bullets (which do damage other blocks), a metal block that takes a ton of hits to
        break, a bomb block that explodes 3 seconds after taking damage, and a chest block that
        reveals a powerup upon breaking.
      - 'This one turned out rather fun, I think. It got rated #90 in the "fun" category for LD31.'
    source: https://github.com/Resonious/breaker
    link: http://resonious.github.io/breaker
    entry: http://ludumdare.com/compo/ludum-dare-31/?action=preview&uid=38940

  - name: A Duel with The Devil
    path: a-duel-with-the-devil
    logline: Side-view grid-based tactical combat.
    image:
      src: /videos/dwtd-preview.webm
      anchor: center
      height: 400px
    video:
      src: /videos/dwtd-good-fixed.webm
    description:
      - My entry for Ludum Dare 33. The theme for that LD was "You are the Monster", which I had
        a hard time working with. I came up with the idea of having an enemy that mimicks the player's
        behavior somehow, which I thought was a neat, somewhat literal interpretation of
        "You are the Monster".
      - I figured if I was going to base the game off of enemy behavior,
        I'd need to have a reasonably complex combat system. I came up with something that's vaguely
        similar to Crypt of The NecroDancer, except with a sidescroller view (and the camera does
        not move). Pressing an arrow key moves the character one cell in the specified direction. The "up"
        direction does somewhat of a jump where the character moves up one cell, and then down one cell after
        a delay. When the player jumps, and then presses the left or right arrow key while still in the air,
        they perform a downward slash in that direction. Pressing the down button blocks incoming attacks.
      - The goal of the game is to move onto your opponent's cell. When each player moves onto each other's
        cell simultaneously, it's a "clash" and no movement happens. It's a weird system, but surprisingly
        easy to get the hang of. I did eventually create a boss enemy that behaves differently based on
        the player's actions during the first several fights, but it was honestly not obvious at all, so
        nobody really understood the connection between this game and the theme. Nevertheless, the game
        ranked number 36 in "fun" and 58 in "overall".
    source: https://github.com/Resonious/dwtd
    link: https://github.com/Resonious/dwtd/releases/tag/ld33
    entry: http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=38940

  - name: Interdimensional Corgi Fishing
    path: corgi-fishing
    logline: Use a magic headlamp to see into the fish dimension.
    image:
      src: /videos/corgi-preview.webm
      anchor: center
      height: '464px'
    video:
      src: /videos/corgi-gameplay.webm
    description:
      - My (and team's) entry for the 2nd Alakajam! The theme was "You can't see everything".
        I ended up with a team much larger than originally anticipated for this one (6 people!),
        which worried me as I suspected communicating with people would use up a lot of time.
        Surely enough, communicating with people did take up a fair amount of time, but the
        productivity boost of the large team proved to make up the difference! Plus it was a
        lot of fun.
      - Admittedly this game's concept is quite bizarre. Our original idea included being
        able to collect magic glasses that change the world when worn, and as a result of
        narrowing things down, it became using a headlamp to view a small portion of another
        world and swap things to and from that world. Because it took us so long to come up
        with enough of a concept to get started, we delayed coming up with any actual gameplay
        until rather late in the jam (and night). It occurred to us after the matter that
        it's maybe strange to collect a bunch of fish in buckets, and then leave the fish
        behind and eat regular dog food.
      - "Team: Nigel Baillie, Jennifer Dailey, Nathan Korth, Daniel Korth, Joe Ambrose, and Sundari Butkiewicz."
    link: https://drive.google.com/file/d/1X0A7wivRNggnGpp7IWO0U2bauzYuEIgQ/view?usp=sharing
    entry: https://alakajam.com/2nd-alakajam/172/interdimensional-corgi-fishing/
