---
# Pug options
pretty: true

# Header info
fullName: Nigel Baillie
bulletPoints:
  - Software engineer
  - University of Michigan student
  - Video game enthusiast

# Project entries
projects:
  - name: Gray Area
    logline: Really bad video game
    image: images/gray-area.webp

  - name: A Duel with The Devil
    logline: Really good video game
    image: images/dwtd.webp
